### ISSUE TITLE
SE Moth and Pteranodon data mixed up/unnecessary in ark_data.json

### ISSUE THREAD

**Issue by mitfry** [Qowyn/ark-tools#25]
Hello!

I noticed this in ark_data.json:

>{
            "package":"/Game/ScorchedEarth/Dinos/Moth/Moth_Character_BP_Base",
            "blueprint":"Moth_Character_BP_Base",
            "class":"Moth_Character_BP_Base_C",
            "name":"Pteranodon"
        },
        {
            "package":"/Game/ScorchedEarth/Dinos/Moth/Moth_Character_BP",
            "blueprint":"Moth_Character_BP",
            "class":"Moth_Character_BP_C",
            "name":"Lymantria"
        },

Ptera's don't exists on SE. Either the name of the first part is incorrect or it can be removed altogether, correct?

**Comment by Qowyn** [comment]
Seems like I'm missing a filter for _Base stuff in my extraction program. Moth_Character_BP_Base is like a prototype thing for the real moth, and it seems WC copied the Pteranodon to create it. And then they didn't change the name because that thing will never be seen in the game.

So yeah: it shouldn't be in there.

**Comment by mitfry** [comment]
Thanks for the reply Qowyn!

Glad I was able to point this out :).

Basically we stumbled upon some code leftovers from a lazy WC dev? ;)

**Comment by Qowyn** [comment]
Should be fixed now. Also added missing data from Ragnarok.

Maybe a lazy dev, but then again you will never see that creature in the game unless you spawn it in.

**Comment by mitfry** [comment]
Thank you for the update! 

I'd say this issue is now solved :)
